### ISSUE TITLE
LPの画像と文章の見え方を整える

### ISSUE THREAD

**Issue by pira0223** [worldclub-sokuniv/xeory_base_child#18]
## What is an issue
< describe what is issue >
**以下の画像のように、LPの画像と文章の見え方を整える**
<img width="773" alt="スクリーンショット 2020-04-30 22 38 10" src="https://user-images.githubusercontent.com/64359567/80722896-dbc97b00-8b3a-11ea-9e4e-2a68ad9d04fb.png">

## How to solve it
< describe or list the solution of the issue >

**Comment by mmfiber** [comment]
* PCの場合は文字に合わせる
* スマフォの場合は写真に合わせる

**Comment by mmfiber** [comment]
@Satosei111997 @pira0223 
https://ssa-6hh205.slack.com/archives/C011PMHQ2SH/p1590493563002000?thread_ts=1590492995.000800&cid=C011PMHQ2SH

**Comment by mmfiber** [comment]
@Satosei111997 
何点か修正できていませんでした。再度調査お願いします。
![image](https://user-images.githubusercontent.com/42595867/82981075-0a495180-a026-11ea-88a7-0376441d9dea.png)
![image](https://user-images.githubusercontent.com/42595867/82981097-16cdaa00-a026-11ea-9b25-d3a590712b87.png)
![image](https://user-images.githubusercontent.com/42595867/82981123-264cf300-a026-11ea-8629-f3ce1c836d99.png)

**Comment by Satosei111997** [comment]
ブロックが左にずれていたものはwp投稿に変なコンテンツがついていたみたいです
記事ページはいけたのですが、記事一覧ページの説明も80%になってしまって、そこを調査しております、もう少しお待ちください。。

**Comment by mmfiber** [comment]
@pira0223 
こちら確認お願いいたします。
スマホ画面で見ると幅が狭く見にくいですが、それは[こちら](https://github.com/worldclub-sokuniv/xeory_base_child/issues/44)で対応いたします。

もし、他に問題が内容でしたらクローズをお願いいたします。

**Comment by mmfiber** [comment]
@pira0223 の代わりに @mmfiber  が確認したのでクローズします。
