### ISSUE TITLE
サムネイル画像を文中上部に表示させない

### ISSUE THREAD

**Issue by pira0223** [worldclub-sokuniv/xeory_base_child#19]
## What is an issue
< describe what is issue >
**サムネイルを文中上部に表示させない**
<img width="962" alt="スクリーンショット 2020-04-30 23 06 27" src="https://user-images.githubusercontent.com/64359567/80723010-03b8de80-8b3b-11ea-8aa3-baa46ad0c52c.png">

## How to solve it
< describe or list the solution of the issue >

**Comment by mmfiber** [comment]
5/16, 17が締め切り

**Comment by mmfiber** [comment]
@Satosei111997 
[こちら](https://docs.google.com/document/d/1hrPdcVGdR5iOWmV6nAgJifJKz17tBuYYKyWusNbvid8/edit)
にアイキャッチとは別に画像を挿入する必要がある旨を記載してください。

また、イシュー作成者に修正した旨を伝え、OKならばこのイシューをクローズしてもらってください。基本的にはイシューを作った人が最後に変更を確認し、クローズします。
