### ISSUE TITLE
タグ検索はフォーカスしなおさないと選択しが表示されない

### ISSUE THREAD

**Issue by mmfiber** [worldclub-sokuniv/xeory_base_child#33]
## 【環境】
windows
## 【ブラウザ / 端末】
chrome
## 【URL（どのページか）】
カテゴリ
## 【内容 / 条件】
入力後も選択肢が表示されるようにする

**Comment by mmfiber** [comment]
local by frywheel で確認できる？

**Comment by Satosei111997** [comment]
@mmfiber 
categories > normal.php 47行目の以下の部分のコメントアウトを戻したのですが、タグをクリックできない（リンクがついていない）状態です。
他にどこか戻す必要があるところってありましたか？

```
<section class="cat-content">
	<header class="cat-header">
            <h1 class="post-title"><?php bzb_title(); ?></h1>
            <?php tag_filter($tags, $tagIDs); ?>
	</header>
	<?php if ( is_category() ) { ?>
		<?php bzb_category_description(); ?>
	<?php } ?>
</section>
```
![Screen Shot 2020-07-13 at 10 34 32](https://user-images.githubusercontent.com/63938631/87262321-7a3b6a80-c4f4-11ea-9ee3-6a7eb7827869.png)

**Comment by mmfiber** [comment]
@Satosei111997 

素晴らしい！
これ結構悩んでできなかったので助かりました！

**Comment by Satosei111997** [comment]
いえいえ、まささんが送ってくれたURLのままに変えただけです笑
