### ISSUE TITLE
インタビュー記事のスマホ画面におけるスタイリング

### ISSUE THREAD

**Issue by Satosei111997** [worldclub-sokuniv/xeory_base_child#44]
## 【ブラウザ / 端末】
スマホ（iphone）

## 【URL（どのページか）】
インタビューページ

## 【内容 / 条件】
related issue: #48 

80%が適用されているため、読みづらい
![S__12959831](https://user-images.githubusercontent.com/63938631/83897442-92e79080-a790-11ea-829c-9d6e55f5dcf5.jpg)

## 【改善案】
@mediaを使う

**Comment by Satosei111997** [comment]
@mmfiber 
2枚目の画像のように@mediaを編集すれば、スマホスタイルができることがわかりましたが、新しく作ったローカルのブランチ（feature-issue44-styling_article_in_smartphone）ではスタイリングをするコンテンツがまだありません。
なので、[こちらのイシュー42](https://github.com/worldclub-sokuniv/xeory_base_child/pull/42)がマージされ次第、編集するという感じで良いでしょうか？もしくは、issue42に上書きする形の方が簡単でしょうか？

↓iphoneでのスタイル
![IMG_4521](https://user-images.githubusercontent.com/63938631/85661558-d2e7c680-b6f1-11ea-842f-69807efe4089.PNG)

↓issue42の上から編集したもの
![Screen Shot 2020-06-25 at 14 39 49](https://user-images.githubusercontent.com/63938631/85661543-cfecd600-b6f1-11ea-8838-f7fa5a416722.png)

**Comment by mmfiber** [comment]
@Satosei111997 

> 2枚目の画像のように@mediaを編集すれば、スマホスタイルができることがわかりましたが、新しく作ったローカルのブランチ（feature-issue44-styling_article_in_smartphone）ではスタイリングをするコンテンツがまだありません。
なので、こちらのイシュー42がマージされ次第、編集するという感じで良いでしょうか？もしくは、issue42に上書きする形の方が簡単でしょうか？

42 が終わってからで構いませんが、コンテンツがないというのはどういう意味でしょうか？
ブランチが変わってもリソースは一緒のはずです。記事とか。

**Comment by Satosei111997** [comment]
すみません、scssをいじるためのクラスやコンテントがscssに存在していないという意味でした。
codeのスクショのpost-contentなどです。
42以降の件、承知しました！

**Comment by mmfiber** [comment]
@Satosei111997 
マージしたので、本番環境で確認お願いします。
