### ISSUE TITLE
ホームページの作成

### ISSUE THREAD

**Issue by mmfiber** [worldclub-sokuniv/xeory_base_child#45]
## 【内容 / 条件】
ホームページの修正

- 記事カテゴリを取得する

- カードの設計
  * 大きいカードをクリックするとカテゴリーページに飛ぶ
  * 小さいカードをクリックすると記事に飛ぶ
  * カード上部にはタグをつける
  * タグをクリックするとタグでソート済みのカテゴリーページに飛ぶ（ここは三上と一緒にやる？）
　（どのタグをつけるか聞く必要あり）
  * カードの画像とタイトルは、記事のサムネイルとタイトルを使う

- スマフォ画面対応

## 【改善案】
https://www.figma.com/file/1YuY2LdQYUM7XsERBaqT03/ssa_web?node-id=2%3A10

**Comment by mmfiber** [comment]
from @Satosei111997 

とりあえず形だけでもここまで来ました！
ただまだ残っているタスクとして、こんな感じです。
①ハッシュタグをつける
②imgがなぜか挿入できない（backgroundカラーにしてます）
③この環境でpxを調整したりしているため、その他の環境や違う縮尺では上手く表示できない
④コードがめちゃくちゃ汚い、同じものを何回も書いているため劇的に長い
お時間空いてる時にタスクについて相談させていただいてもいいでしょうか？
日曜であれば10:30~21時で空いています。
タスクの詳細はコメントに貼っておきます
③④については、できる限り直せるように工夫してみます。

**Comment by mmfiber** [comment]
from @Satosei111997 

①ハッシュタグをつける
・何を知りたいか→どうすれば該当ハッシュタグのデータをもってこれるか、ハッシュタグをcardにつけられるか、細かいデザインはどうするのか
・どこまで調べたのか→調べ方が分からず、ssaのtagに関するコードを軽くいじってみた程度
・どこで詰まっているのか→ハッシュタグをどう持ってきて表示するのかが分からない
・自分はどうすればいいと思っているのか→jsの$tags周辺にtagを持ってくる指示がありそうなのでそれをfront-pageにも埋め込む？

**Comment by mmfiber** [comment]
from @Satosei111997 

②imgが挿入できない
・何を知りたいか→なぜ一色背景にしてるboxの場所にimgが挿入できないか
・どこまで調べたのか→htmlのimg挿入
・どこで詰まっているのか→imgファイルのフォルダを変えたり、既存のimg(no-image)を使ってみたり、src=""の中身をいじってみたりしたが表示されず、16×16pxくらいのfileマーク（:file_folder:こんな感じ）が表示されるだけ
・自分はどうすればいいと思っているのか→分かりません

**Comment by mmfiber** [comment]
@Satosei111997 

> ①ハッシュタグをつける ...

下記の方法で取得できないですか
https://github.com/worldclub-sokuniv/xeory_base_child/blob/c083dcf1fd234690c553a33f57f7837b20b160c1/categories/normal.php#L2-L37

あと、多分JSは必要ない。

**Comment by mmfiber** [comment]
@Satosei111997 

> ②imgが挿入できない...

これはたぶん、src の設定がうまく行っていないから。デベロッパーツールで、src に写真がある絶対パスで指定してみてください。（例：https://worldclub-soka.com/wp-content/uploads/2020/05/IMG_2672.jpg）

**Comment by Satosei111997** [comment]
@mmfiber 
> これはたぶん、src の設定がうまく...

wpにあるものじゃないとだめなんですね、できました！

**Comment by mmfiber** [comment]
@Satosei111997 

> wpにあるものじゃないとだめなんですね、できました！

ドメインが以下のパスで表現できる位置にないと無理ですね。（URLで表現できる位置）
もしくは別のサーバーを立てて、そこからURLを叩いて画像を取ってくる。本当はこちらの方がいいと思っています。理由は以下です。

- サーバの負担が減る

- 画像の読み込みを待たずにコンテンツを表示できる

参考にしたエンジャパンも上記の方法をとっていてAWS の S3 というサービスを使っています。

**Comment by mmfiber** [comment]
@mmfiber 
修正したので確認お願いします
